# https://dart.dev/tools/linter-rules  

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    avoid_print: true
    prefer_single_quotes: false
    sort_constructors_first: true
    sort_child_properties_last: true