name: weather_app
description: A weather app that uses the OpenWeatherMap API.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.0.0
  intl: ^0.18.1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
  package_info_plus: ^4.0.2

  rounded_input_button:
    git:
      url: https://github.com/neurothrone/rounded_input_button.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  image_path: "assets/images/app-icon.png"
  android: true
  adaptive_icon_background: "#023047"
  adaptive_icon_foreground: "assets/images/app-icon-original.png"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#023047"
  image: "assets/images/app-icon-original.png"
  ios: true
  android: true
  android_12:
    color: "#023047"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
