name: weather_app
description: A weather app that uses the OpenWeatherMap API.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.0.0
  intl: ^0.18.1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.5

  rounded_input_button:
    git:
      url: https://github.com/neurothrone/rounded_input_button.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
